### ISSUE TITLE
why select the farthest nodes?

### ISSUE THREAD

**Issue by GuodongFan** [yichen928/ActiveFT#3]
_, ids_sort = torch.sort(dist, dim=1, descending=True)

**Comment by yichen928** [comment]
Thank you for your interest.

"dist" is actually cosine similarity here, so this line is selecting the closest nodes to each parameter (Eq. 12 of our paper).

**Comment by yichen928** [comment]
I am not sure, but I think many active learning methods focus on high-level discriminative features (such as CoreSet) so they do not care much for details important for generation.

**Comment by yichen928** [comment]
I am not quite familiar with generative models. Maybe you can try this paper: https://arxiv.org/abs/1905.03677. This may handle fine-grained tasks.
