### ISSUE TITLE
"RuntimeError: Function 'ExpBackward' returned nan values in its 0th output"

### ISSUE THREAD

**Issue by bardisafa** [yichen928/ActiveFT#4]
Hi,
I encounter nan/inf values in the loss gradients which seem to occur due to the small chosen temperature (0.07) followed by an exponential function. I get the same error even while using temperature=1. Can you please let me know if you have encountered the same issue and how to prevent it from happening? Did you use any clamping with the defined values as below which are in the codebase? `torch.autograd.set_detect_anomaly(True)
eps = 1e-10
infty = 1e10
`

**Comment by yichen928** [comment]
Thanks for your interest. I think I never encountered this problem. I did not use any extra techniques except those in the released code. Maybe you can first check whether the nan/inf came from the gradient or other previous computation? If it indeed came from the gradient, you may consider decreasing the learning rate.

**Comment by bardisafa** [comment]
Thanks for the response.
The inf values happen during the computation. Specifically, in the get_loss() method,
`def get_loss(self):
        pdb.set_trace()
        centroids = F.normalize(self.centroids, dim=1)
        prod = torch.matmul(self.features, centroids.transpose(1, 0))  # (n, k)
        prod = prod / self.temperature
        prod_exp = torch.exp(prod)
        prod_exp_pos, pos_k = torch.max(prod_exp, dim=1)  # (n, )

        cent_prod = torch.matmul(centroids.detach(), centroids.transpose(1, 0))  # (k, k)
        cent_prod = cent_prod / self.temperature
        cent_prod_exp = torch.exp(cent_prod)
        cent_prob_exp_sum = torch.sum(cent_prod_exp, dim=0)  # (k, )

        J = torch.log(prod_exp_pos) - torch.log(prod_exp_pos + cent_prob_exp_sum[pos_k] * self.balance)
        J = -torch.mean(J)

        return J`
Here is the values of the prod_exp with temperature=0.07 (features are normalized):
`Pdb) prod_exp
tensor([[11424.,  2672., 27408.,  ..., 20688., 19584., 10008.],
        [ 3680.,  7264., 41792.,  ..., 17152.,    inf, 41792.],
        [ 1282.,  4172., 15024.,  ...,    inf, 13568., 10008.],
        ...,
        [ 5272., 26160., 30336.,  ...,  4580., 30112., 34656.],
        [34912.,  5612.,  2610.,  ...,  2242.,  5884.,  3028.],
        [ 3028.,  3950., 13464.,  ...,  4840., 30336., 15744.]],
       device='cuda:0', dtype=torch.float16, grad_fn=<ExpBackward>)`

**Comment by yichen928** [comment]
Can you check the value before the exp operation? Since the features are normalized, the product cannot exceed 1. Even with the low temperature 0.07, it is still hard to overflow. You may also try to increase the temperature and see where the overflow appears.
