### ISSUE TITLE
The coreset baseline

### ISSUE THREAD

**Issue by Tristan-Liu-13** [yichen928/ActiveFT#5]
Dear author,
I have a question about the coreset baseline. I wonder in your paper, how the coreset baseline is implemented. I search repositories about coreset, but except the official code, others only implement the k-center-greedy version (The official code seems another language I don't know). Are you using the greedy version, or the robust version? (If the robust version, could you please provide the code)
Looking forward to your reply.

**Comment by yichen928** [comment]
Thanks for your interest. I am also using greedy version of CoreSet for this paper.

**Comment by Tristan-Liu-13** [comment]
get it
thanks for your quick reply!
